twitterclone/base/urls.py
from django.conf.urls import url, include

from .views import *

app_name = "base"

urlpatterns = [
    url(r'^$', LandingPageView.as_view(), name="index"),
    url(r'^about/$', AboutPageView.as_view(), name="about"),
    url(r'^list/tweets/$', TweetListView.as_view(), name="list-tweets"),
]

twitterclone/twitterclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitterclone/base/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Tweet(models.Model):
	title = models.CharField(max_length=280)
	image = models.ImageField(upload_to="media/tweet_pics")

class Checkin(models.Model):
	name = models.CharField(max_length=280)
	surname = models.CharField(max_length=280)
	profile_pic = models.ImageField(upload_to="media/profile_pic")
	checkin_number = models.IntegerField(default=0)
	# this will automatically add a date and time when someone checks in
	timestamp = models.DateTimeField(auto_now_add=True) 

twitterclone/base/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from .models import Tweet

from django.views.generic import (
	TemplateView, 
	ListView
	)


class LandingPageView(TemplateView):
	template_name = "base/index.html"

class AboutPageView(TemplateView):
	template_name = "base/about.html"

class TweetListView(ListView):
	model = Tweet

	def get_queryset(self):
		return Tweet.objects.all()

twitterclone/base/templates/base/about.html
{% extends 'base/base.html' %}

{% block title %}
About Page
{% endblock %}

{% block body %}
<h2>About Me</h2>
<p>this give detail on a person. </p>

<a href="{% url 'base:index' %}">Go Back</a>
{% endblock %}

twitterclone/base/templates/base/base.html
<html>
    <head>
         <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
     {% block body %}{% endblock %}
    </body>
</html>

twitterclone/base/templates/base/index.html
{% extends 'base/base.html' %}

{% block title %}
this is the title
{% endblock %}

{% block body %}
<h2> this is the header</h2>
<p>this is for paragraphs</p>

<a href="{% url 'base:about' %}">Go to About Page</a>
<br>
<br>
<a href="{% url 'base:list-tweets' %}">Go to List of Tweets Page</a>
{% endblock %}

twitterclone/base/templates/base/tweet_list.html
{% extends 'base/base.html' %}

{% block title %}
Listing all tweets
{% endblock %}

{% block body %}
<h2>All Tweets</h2>
<p>here are all the tweets</p>

<a href="{% url 'base:index' %}">Go Home</a>

<br>
<ul>
	{% for object in object_list %}
	<li>
		<div>
			{{ object.title | title }}
			<br>
			<img src="{{ object.image.url }}" alt="" height="200" width="200">
		</div>
	</li>
	{% endfor %}
</ul>
{% endblock %}